- name: copy magento archive
  copy: src=magento-1.8.1.0.tar.gz dest=/tmp/magento-1.8.1.0.tar.gz

- name: extract magento archive
  shell: tar xzf /tmp/magento-1.8.1.0.tar.gz chdir=/opt creates=/opt/magento/LICENSE.html

- name: fix permissions
  file: path=/opt/magento owner=vagrant group=vagrant mode=0755 recurse=yes
