---
# testing ansible

- hosts: develop-vm
  sudo: yes
  tasks:
   - name: run apt-get update
     apt: update_cache=yes cache_valid_time=86400

#   - name: update all packages to the latest version
#     apt: upgrade=full

   - name: install tasksel
     apt: pkg=tasksel state=latest

   - name: install debconf-utils
     apt: pkg=debconf-utils state=latest

   # https://github.com/phred/5minbootstrap/blob/master/bootstrap.yml
   - name: copy debconf selections so that tasksel can configure itself non-interactively
     copy: src=config/debconf_selections dest=/tmp/debconf_selections

   - name: set up debconf with selections
     command: debconf-set-selections /tmp/debconf_selections

   # http://crosswire.org/~jmarsden/talks/lamp-install/lamp-install.txt
   - name: install lamp-server with tasksel
     command: tasksel install lamp-server

   - name: install phpmyadmin
     apt: pkg=phpmyadmin state=latest

   - name: install curl
     apt: pkg=curl state=latest

   - name: extract magento archive
     shell: tar xzf /vagrant/provisioning/magento-1.8.1.0.tar.gz chdir=/opt creates=/opt/magento/LICENSE.html

   - name: fix permissions
     file: path=/opt/magento owner=vagrant group=vagrant mode=0755 recurse=yes
