- name: run apt-get update
  apt: update_cache=yes cache_valid_time=86400

- name: update all packages to the latest version
  apt: upgrade=full

- name: install tasksel
  apt: pkg=tasksel state=latest

- name: install debconf-utils
  apt: pkg=debconf-utils state=latest

# https://github.com/phred/5minbootstrap/blob/master/bootstrap.yml
- name: copy debconf selections so that tasksel can configure itself non-interactively
  copy: src=debconf_selections dest=/tmp/debconf_selections

- name: set up debconf with selections
  command: debconf-set-selections /tmp/debconf_selections

# http://crosswire.org/~jmarsden/talks/lamp-install/lamp-install.txt
- name: install lamp-server with tasksel
  command: tasksel install lamp-server

- name: install phpmyadmin
  apt: pkg=phpmyadmin state=latest

- name: install curl
  apt: pkg=curl state=latest
